# Generated by Django 3.2.4 on 2023-05-25 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('searching_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Truck',
            new_name='Machine',
        ),
        migrations.RenameField(
            model_name='machine',
            old_name='carrying_capacity',
            new_name='capacity',
        ),
        migrations.RenameField(
            model_name='machine',
            old_name='truck_number',
            new_name='number',
        ),
        migrations.AddField(
            model_name='location',
            name='latitude',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='longitude',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='location',
            name='zip',
            field=models.CharField(max_length=10),
        ),
        migrations.DeleteModel(
            name='Shipment',
        ),
        migrations.AddField(
            model_name='cargo',
            name='delivery_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='searching_app.location'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='pickup_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickups', to='searching_app.location'),
        ),
    ]
