# Generated by Django 3.2.4 on 2023-05-25 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('searching_app', '0002_auto_20230526_0014'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='zip',
            new_name='zip_code',
        ),
    ]
